In [1]:
import pandas as pd

In [2]:
with open("access.log" ,"r") as file:
    lines = file.readlines()

logs_data=pd.DataFrame(lines,columns=['log'])

In [3]:
logs_data

                                                       log
0        in24.inetnebr.com - - [01/Aug/1995:00:00:01 -0...
1        uplherc.upl.com - - [01/Aug/1995:00:00:07 -040...
2        uplherc.upl.com - - [01/Aug/1995:00:00:08 -040...
3        uplherc.upl.com - - [01/Aug/1995:00:00:08 -040...
4        uplherc.upl.com - - [01/Aug/1995:00:00:08 -040...
...                                                    ...
1569893  gatekeeper.uccu.com - - [31/Aug/1995:23:59:49 ...
1569894  gatekeeper.uccu.com - - [31/Aug/1995:23:59:49 ...
1569895  cys-cap-9.wyoming.com - - [31/Aug/1995:23:59:5...
1569896  www-c8.proxy.aol.com - - [31/Aug/1995:23:59:52...
1569897  cindy.yamato.ibm.co.jp - - [31/Aug/1995:23:59:...

[1569898 rows x 1 columns]

In [4]:
pattern = r'(\S+) \S+ \S+ \[(.*?)\] "(\S+) (.*?) (\S+)" (\d{3}) (\S+)'

logs_data[['ip_address', 'time_stamp', 'http_method_type', 'requested_url', 'protocol', 'status', 'size']] = (
    logs_data['log'].str.extract(pattern)
)

In [5]:
logs_data.head()

,log,ip_address,time_stamp,http_method_type,requested_url,protocol,status,size
0,in24.inetnebr.com - - [01/Aug/1995:00:00:01 -0...,in24.inetnebr.com,01/Aug/1995:00:00:01 -0400,GET,/shuttle/missions/sts-68/news/sts-68-mcc-05.txt,HTTP/1.0,200,1839
1,uplherc.upl.com - - [01/Aug/1995:00:00:07 -040...,uplherc.upl.com,01/Aug/1995:00:00:07 -0400,GET,/,HTTP/1.0,304,0
2,uplherc.upl.com - - [01/Aug/1995:00:00:08 -040...,uplherc.upl.com,01/Aug/1995:00:00:08 -0400,GET,/images/ksclogo-medium.gif,HTTP/1.0,304,0
3,uplherc.upl.com - - [01/Aug/1995:00:00:08 -040...,uplherc.upl.com,01/Aug/1995:00:00:08 -0400,GET,/images/MOSAIC-logosmall.gif,HTTP/1.0,304,0
4,uplherc.upl.com - - [01/Aug/1995:00:00:08 -040...,uplherc.upl.com,01/Aug/1995:00:00:08 -0400,GET,/images/USA-logosmall.gif,HTTP/1.0,304,0

# Data Cleaning

### IP ADDRESS COLUMN

In [6]:
logs_data["ip_address"].unique()

array(['in24.inetnebr.com', 'uplherc.upl.com',
       'ix-esc-ca2-07.ix.netcom.com', ..., 'dffl6-14.gate.net',
       '137.229.105.152', '198.146.93.224'], dtype=object)

In [7]:
logs_data["ip_address"].value_counts()

ip_address
edams.ksc.nasa.gov         6528
piweba4y.prodigy.com       4846
163.206.89.4               4791
piweba5y.prodigy.com       4607
piweba3y.prodigy.com       4416
                           ...
199.172.142.107               1
133.56.112.12                 1
sojus.strm.ing.tu-bs.de       1
ccmac1.unican.es              1
mcimcwk12.san.uc.edu          1
Name: count, Length: 74969, dtype: int64

### HTTP METHOD COLUMN

In [8]:
logs_data["http_method_type"].unique()

array(['GET', nan, 'POST', 'HEAD'], dtype=object)

In [9]:
logs_data["http_method_type"].value_counts()

http_method_type
GET     1563829
HEAD       3965
POST        111
Name: count, dtype: int64

### TIME STAMP COLUMN

In [10]:
logs_data["time_stamp"].unique()

array(['01/Aug/1995:00:00:01 -0400', '01/Aug/1995:00:00:07 -0400',
       '01/Aug/1995:00:00:08 -0400', ..., '31/Aug/1995:23:59:49 -0400',
       '31/Aug/1995:23:59:52 -0400', '31/Aug/1995:23:59:53 -0400'],
      dtype=object)

In [11]:
logs_data["requested_url"].unique()

array(['/shuttle/missions/sts-68/news/sts-68-mcc-05.txt', '/',
       '/images/ksclogo-medium.gif', ...,
       '/cgi-bin/imagemap/index69?675,97',
       '/cgi-bin/imagemap/index69?682,101',
       '/cgi-bin/imagemap/index69?682,144'], dtype=object)

### PROTOCOL COLUMN

In [12]:
logs_data["protocol"].value_counts()

protocol
HTTP/1.0                              1567112
<berend@blazemonger.pc.cc.cmu.edu>        624
HTTP/V1.0                                 163
(MILA)</a>                                  1
headers                                     1
of                                          1
Ships                                       1
a                                           1
homepage</a><hr>                            1
Name: count, dtype: int64

In [13]:
valid_protocols = ["HTTP/1.0", "HTTP/1.1"]

invalid = logs_data[~logs_data["protocol"].isin(valid_protocols)]

print(invalid[["log", "protocol"]].count())

log         2786
protocol     793
dtype: int64

In [14]:
logs_data = logs_data[
    logs_data["protocol"].isin(["HTTP/1.0", "HTTP/1.1"])
]

In [15]:
logs_data["protocol"].value_counts()

protocol
HTTP/1.0    1567112
Name: count, dtype: int64

### STATUS COLUMN

In [16]:
logs_data["status"].unique()

array(['200', '304', '302', '404', '403', '500', '501'], dtype=object)

In [17]:
logs_data["status"].value_counts()

status
200    1396349
304     134146
302      26472
404       9944
403        171
501         27
500          3
Name: count, dtype: int64

In [18]:
logs_data["size"].value_counts()

size
0         140410
786        77706
1204       63689
363        58289
234        57952
           ...
36716          1
142983         1
1649           1
1658           1
1663           1
Name: count, Length: 7623, dtype: int64

In [37]:
logs_data = logs_data[logs_data["size"].str.contains(r'\d') != False]

In [19]:
logs_data = logs_data.drop(columns ="log")

In [38]:
logs_data.head()

,ip_address,time_stamp,http_method_type,requested_url,protocol,status,size
0,in24.inetnebr.com,1995-08-01 00:00:01-04:00,GET,/shuttle/missions/sts-68/news/sts-68-mcc-05.txt,HTTP/1.0,200,1839
1,uplherc.upl.com,1995-08-01 00:00:07-04:00,GET,/,HTTP/1.0,304,0
2,uplherc.upl.com,1995-08-01 00:00:08-04:00,GET,/images/ksclogo-medium.gif,HTTP/1.0,304,0
3,uplherc.upl.com,1995-08-01 00:00:08-04:00,GET,/images/MOSAIC-logosmall.gif,HTTP/1.0,304,0
4,uplherc.upl.com,1995-08-01 00:00:08-04:00,GET,/images/USA-logosmall.gif,HTTP/1.0,304,0

# DATA TYPE CORRECTION

In [40]:
logs_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1553068 entries, 0 to 1569897
Data columns (total 7 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   ip_address        1553068 non-null  object
 1   time_stamp        1553068 non-null  datetime64[ns, UTC-04:00]
 2   http_method_type  1553068 non-null  object
 3   requested_url     1553068 non-null  object
 4   protocol          1553068 non-null  object
 5   status            1553068 non-null  int64
 6   size              1553068 non-null  int64
dtypes: datetime64[ns, UTC-04:00](1), int64(2), object(4)
memory usage: 94.8+ MB

In [22]:
logs_data["time_stamp"] = pd.to_datetime(logs_data["time_stamp"], format="%d/%b/%Y:%H:%M:%S %z")
logs_data["status"] = logs_data["status"].astype(int)
logs_data["size"] =logs_data["size"].astype(int)

### CHECK AND REMOVE NULL VALUES

In [41]:
logs_data.isnull().sum()

ip_address          0
time_stamp          0
http_method_type    0
requested_url       0
protocol            0
status              0
size                0
dtype: int64

### CHECK AND REMOVE DUPLICATE ROWS

In [47]:
logs_data[logs_data.duplicated(keep=False)]

,ip_address,time_stamp,http_method_type,requested_url,protocol,status,size
2068,www-c1.proxy.aol.com,1995-08-01 01:21:52-04:00,GET,/history/apollo/apollo.html,HTTP/1.0,200,3260
2069,www-c1.proxy.aol.com,1995-08-01 01:21:52-04:00,GET,/history/apollo/apollo.html,HTTP/1.0,200,3260
31384,www-d2.proxy.aol.com,1995-08-01 13:53:13-04:00,GET,/images/,HTTP/1.0,200,17688
31385,www-d2.proxy.aol.com,1995-08-01 13:53:13-04:00,GET,/images/,HTTP/1.0,200,17688
42865,www-a1.proxy.aol.com,1995-08-03 13:10:12-04:00,GET,/shuttle/missions/sts-69/images/images.html,HTTP/1.0,200,2443
42866,www-a1.proxy.aol.com,1995-08-03 13:10:12-04:00,GET,/shuttle/missions/sts-69/images/images.html,HTTP/1.0,200,2443
45074,128.159.146.40,1995-08-03 13:46:33-04:00,GET,/ksc.html,HTTP/1.0,200,7034
45075,128.159.146.40,1995-08-03 13:46:33-04:00,GET,/ksc.html,HTTP/1.0,200,7034
45206,192.215.71.55,1995-08-03 13:50:18-04:00,GET,/history/history.html,HTTP/1.0,200,1602
45207,192.215.71.55,1995-08-03 13:50:18-04:00,GET,/history/history.html,HTTP/1.0,200,1602
45340,192.215.71.55,1995-08-03 13:53:47-04:00,GET,/history/apollo/apollo.html,HTTP/1.0,200,3260
45342,192.215.71.55,1995-08-03 13:53:47-04:00,GET,/history/apollo/apollo.html,HTTP/1.0,200,3260
46299,128.217.61.8,1995-08-03 14:07:36-04:00,GET,/ksc.html,HTTP/1.0,200,7034
46300,128.217.61.8,1995-08-03 14:07:36-04:00,GET,/ksc.html,HTTP/1.0,200,7034
46306,128.217.61.8,1995-08-03 14:07:40-04:00,GET,/images/ksclogo-medium.gif,HTTP/1.0,200,5866
46307,128.217.61.8,1995-08-03 14:07:40-04:00,GET,/images/ksclogo-medium.gif,HTTP/1.0,200,5866
46308,128.217.61.8,1995-08-03 14:07:43-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
46309,128.217.61.8,1995-08-03 14:07:43-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
46310,128.217.61.8,1995-08-03 14:07:44-04:00,GET,/images/MOSAIC-logosmall.gif,HTTP/1.0,200,363
46312,128.217.61.8,1995-08-03 14:07:44-04:00,GET,/images/MOSAIC-logosmall.gif,HTTP/1.0,200,363
46313,128.217.61.8,1995-08-03 14:07:45-04:00,GET,/images/USA-logosmall.gif,HTTP/1.0,200,234
46314,128.217.61.8,1995-08-03 14:07:45-04:00,GET,/images/USA-logosmall.gif,HTTP/1.0,200,234
46315,128.217.61.8,1995-08-03 14:07:46-04:00,GET,/images/WORLD-logosmall.gif,HTTP/1.0,200,669
46316,128.217.61.8,1995-08-03 14:07:46-04:00,GET,/images/WORLD-logosmall.gif,HTTP/1.0,200,669
46490,client-71-55.online.apple.com,1995-08-03 14:10:56-04:00,GET,/ksc.html,HTTP/1.0,200,7034
46491,client-71-55.online.apple.com,1995-08-03 14:10:56-04:00,GET,/ksc.html,HTTP/1.0,200,7034
46535,client-71-55.online.apple.com,1995-08-03 14:11:41-04:00,GET,/shuttle/missions/sts-70/movies/movies.html,HTTP/1.0,200,2979
46536,client-71-55.online.apple.com,1995-08-03 14:11:41-04:00,GET,/shuttle/missions/sts-70/movies/movies.html,HTTP/1.0,200,2979
51956,www,1995-08-03 15:30:45-04:00,GET,/elv/elvpage.htm,HTTP/1.0,200,9581
51960,www,1995-08-03 15:30:45-04:00,GET,/elv/elvpage.htm,HTTP/1.0,200,9581
53618,128.159.127.35,1995-08-03 15:51:15-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
53620,128.159.127.35,1995-08-03 15:51:15-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
59970,hpcvsop.cv.hp.com,1995-08-03 17:20:12-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
59971,hpcvsop.cv.hp.com,1995-08-03 17:20:12-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
63365,www-c2.proxy.aol.com,1995-08-03 18:15:40-04:00,GET,/,HTTP/1.0,200,7034
63367,www-c2.proxy.aol.com,1995-08-03 18:15:40-04:00,GET,/,HTTP/1.0,200,7034
63369,www-c4.proxy.aol.com,1995-08-03 18:15:40-04:00,GET,/,HTTP/1.0,200,7034
63370,www-c4.proxy.aol.com,1995-08-03 18:15:40-04:00,GET,/,HTTP/1.0,200,7034
63374,www-d4.proxy.aol.com,1995-08-03 18:15:41-04:00,GET,/,HTTP/1.0,200,7034
63375,www-d4.proxy.aol.com,1995-08-03 18:15:41-04:00,GET,/,HTTP/1.0,200,7034
63376,www-d4.proxy.aol.com,1995-08-03 18:15:41-04:00,GET,/,HTTP/1.0,200,7034
65903,disarray.demon.co.uk,1995-08-03 19:25:57-04:00,GET,/shuttle/missions/sts-69/mission-sts-69.html,HTTP/1.0,200,11264
65904,disarray.demon.co.uk,1995-08-03 19:25:57-04:00,GET,/shuttle/missions/sts-69/mission-sts-69.html,HTTP/1.0,200,11264
68703,www-b4.proxy.aol.com,1995-08-03 20:42:23-04:00,GET,/,HTTP/1.0,200,7034
68704,www-b4.proxy.aol.com,1995-08-03 20:42:23-04:00,GET,/,HTTP/1.0,200,7034
81110,rzsun01.rrz.uni-hamburg.de,1995-08-04 04:20:55-04:00,GET,/shuttle/missions/sts-69/count69.gif,HTTP/1.0,200,46053
81111,rzsun01.rrz.uni-hamburg.de,1995-08-04 04:20:55-04:00,GET,/shuttle/missions/sts-69/count69.gif,HTTP/1.0,200,46053
96434,rm101b3.ageng.vt.edu,1995-08-04 10:59:57-04:00,GET,/facilities/sspf.html,HTTP/1.0,304,0
96435,rm101b3.ageng.vt.edu,1995-08-04 10:59:57-04:00,GET,/facilities/sspf.html,HTTP/1.0,304,0
106162,magicall.dacom.co.kr,1995-08-04 13:33:54-04:00,GET,/,HTTP/1.0,200,7034
106163,magicall.dacom.co.kr,1995-08-04 13:33:54-04:00,GET,/,HTTP/1.0,200,7034
108078,ddt.wri.com,1995-08-04 13:58:17-04:00,GET,/elv/DELTA/delta.gif,HTTP/1.0,200,2244
108079,ddt.wri.com,1995-08-04 13:58:17-04:00,GET,/elv/DELTA/delta.gif,HTTP/1.0,200,2244
113636,sdn_b6_f02_ip.dny.rockwell.com,1995-08-04 15:28:34-04:00,GET,/,HTTP/1.0,200,7034
113637,sdn_b6_f02_ip.dny.rockwell.com,1995-08-04 15:28:34-04:00,GET,/,HTTP/1.0,200,7034
113643,sdn_b6_f02_ip.dny.rockwell.com,1995-08-04 15:28:42-04:00,GET,/images/WORLD-logosmall.gif,HTTP/1.0,200,669
113644,sdn_b6_f02_ip.dny.rockwell.com,1995-08-04 15:28:42-04:00,GET,/images/WORLD-logosmall.gif,HTTP/1.0,200,669
113650,sdn_b6_f02_ip.dny.rockwell.com,1995-08-04 15:28:46-04:00,GET,/images/ksclogo-medium.gif,HTTP/1.0,200,5866
113652,sdn_b6_f02_ip.dny.rockwell.com,1995-08-04 15:28:46-04:00,GET,/images/ksclogo-medium.gif,HTTP/1.0,200,5866
121855,www-b5.proxy.aol.com,1995-08-04 17:26:40-04:00,GET,/images/,HTTP/1.0,200,17688
121856,www-b5.proxy.aol.com,1995-08-04 17:26:40-04:00,GET,/images/,HTTP/1.0,200,17688
122854,www-d4.proxy.aol.com,1995-08-04 17:48:04-04:00,GET,/shuttle/missions/sts-69/,HTTP/1.0,200,3286
122855,www-d4.proxy.aol.com,1995-08-04 17:48:04-04:00,GET,/shuttle/missions/sts-69/,HTTP/1.0,200,3286
126925,www-b5.proxy.aol.com,1995-08-04 19:33:09-04:00,GET,/images/ksclogo.gif,HTTP/1.0,200,14298
126926,www-b5.proxy.aol.com,1995-08-04 19:33:09-04:00,GET,/images/ksclogo.gif,HTTP/1.0,200,14298
127428,131.171.130.221,1995-08-04 19:45:06-04:00,GET,/images/KSC-logosmall.gif,HTTP/1.0,200,1204
127433,131.171.130.221,1995-08-04 19:45:06-04:00,GET,/images/KSC-logosmall.gif,HTTP/1.0,200,1204
128762,www.usq.edu.au,1995-08-04 20:23:20-04:00,GET,/images/ksclogo-medium.gif,HTTP/1.0,200,5866
128763,www.usq.edu.au,1995-08-04 20:23:20-04:00,GET,/images/ksclogo-medium.gif,HTTP/1.0,200,5866
129872,www-c2.proxy.aol.com,1995-08-04 20:58:47-04:00,GET,/statistics/statistics.html,HTTP/1.0,200,2813
129873,www-c2.proxy.aol.com,1995-08-04 20:58:47-04:00,GET,/statistics/statistics.html,HTTP/1.0,200,2813
143562,ix-bos7-11.ix.netcom.com,1995-08-05 09:20:08-04:00,GET,/shuttle/technology/sts-newsref/stsref-toc.html,HTTP/1.0,200,84905
143563,ix-bos7-11.ix.netcom.com,1995-08-05 09:20:08-04:00,GET,/shuttle/technology/sts-newsref/stsref-toc.html,HTTP/1.0,200,84905
163725,pipe2.h1.usa.pipeline.com,1995-08-05 22:04:32-04:00,GET,/icons/blank.xbm,HTTP/1.0,200,509
163726,pipe2.h1.usa.pipeline.com,1995-08-05 22:04:32-04:00,GET,/icons/blank.xbm,HTTP/1.0,200,509
163727,pipe2.h1.usa.pipeline.com,1995-08-05 22:04:32-04:00,GET,/icons/menu.xbm,HTTP/1.0,200,527
163728,pipe2.h1.usa.pipeline.com,1995-08-05 22:04:32-04:00,GET,/icons/menu.xbm,HTTP/1.0,200,527
163729,pipe2.h1.usa.pipeline.com,1995-08-05 22:04:33-04:00,GET,/icons/image.xbm,HTTP/1.0,200,509
163730,pipe2.h1.usa.pipeline.com,1995-08-05 22:04:33-04:00,GET,/icons/image.xbm,HTTP/1.0,200,509
163989,client-71-206.online.apple.com,1995-08-05 22:11:43-04:00,GET,/shuttle/missions/sts-70/mission-sts-70.html,HTTP/1.0,200,20304
163990,client-71-206.online.apple.com,1995-08-05 22:11:43-04:00,GET,/shuttle/missions/sts-70/mission-sts-70.html,HTTP/1.0,200,20304
164755,www-a2.proxy.aol.com,1995-08-05 22:40:59-04:00,GET,/images/,HTTP/1.0,200,17688
164756,www-a2.proxy.aol.com,1995-08-05 22:40:59-04:00,GET,/images/,HTTP/1.0,200,17688
167635,www-d3.proxy.aol.com,1995-08-06 00:25:42-04:00,GET,/ksc.html,HTTP/1.0,200,7034
167636,www-d3.proxy.aol.com,1995-08-06 00:25:42-04:00,GET,/ksc.html,HTTP/1.0,200,7034
173357,www-b4.proxy.aol.com,1995-08-06 06:19:11-04:00,GET,/ksc.html,HTTP/1.0,200,7034
173358,www-b4.proxy.aol.com,1995-08-06 06:19:11-04:00,GET,/ksc.html,HTTP/1.0,200,7034
173390,www-b4.proxy.aol.com,1995-08-06 06:20:42-04:00,GET,/shuttle/missions/sts-69/mission-sts-69.html,HTTP/1.0,200,11264
173391,www-b4.proxy.aol.com,1995-08-06 06:20:42-04:00,GET,/shuttle/missions/sts-69/mission-sts-69.html,HTTP/1.0,200,11264
173410,www-b4.proxy.aol.com,1995-08-06 06:22:13-04:00,GET,/shuttle/countdown/,HTTP/1.0,200,4673
173411,www-b4.proxy.aol.com,1995-08-06 06:22:13-04:00,GET,/shuttle/countdown/,HTTP/1.0,200,4673
173427,www-b4.proxy.aol.com,1995-08-06 06:23:24-04:00,GET,"/cgi-bin/imagemap/countdown69?68,162",HTTP/1.0,302,111
173428,www-b4.proxy.aol.com,1995-08-06 06:23:24-04:00,GET,"/cgi-bin/imagemap/countdown69?68,162",HTTP/1.0,302,111
173429,www-b4.proxy.aol.com,1995-08-06 06:23:25-04:00,GET,"/cgi-bin/imagemap/countdown69?68,162",HTTP/1.0,302,111
173430,www-b4.proxy.aol.com,1995-08-06 06:23:25-04:00,GET,"/cgi-bin/imagemap/countdown69?68,162",HTTP/1.0,302,111
173431,www-b4.proxy.aol.com,1995-08-06 06:23:25-04:00,GET,"/cgi-bin/imagemap/countdown69?68,162",HTTP/1.0,302,111
177895,www-c5.proxy.aol.com,1995-08-06 11:25:01-04:00,GET,/shuttle/resources/orbiters/atlantis.html,HTTP/1.0,200,7025
177896,www-c5.proxy.aol.com,1995-08-06 11:25:01-04:00,GET,/shuttle/resources/orbiters/atlantis.html,HTTP/1.0,200,7025
177962,www-c5.proxy.aol.com,1995-08-06 11:26:46-04:00,GET,/shuttle/missions/sts-71/mission-sts-71.html,HTTP/1.0,200,13644
177963,www-c5.proxy.aol.com,1995-08-06 11:26:46-04:00,GET,/shuttle/missions/sts-71/mission-sts-71.html,HTTP/1.0,200,13644
178067,www-c5.proxy.aol.com,1995-08-06 11:29:40-04:00,GET,/shuttle/resources/orbiters/enterprise.html,HTTP/1.0,200,9732
178068,www-c5.proxy.aol.com,1995-08-06 11:29:40-04:00,GET,/shuttle/resources/orbiters/enterprise.html,HTTP/1.0,200,9732
181124,www-c2.proxy.aol.com,1995-08-06 13:46:00-04:00,GET,/images/263_small.jpg,HTTP/1.0,200,159673
181125,www-c2.proxy.aol.com,1995-08-06 13:46:00-04:00,GET,/images/263_small.jpg,HTTP/1.0,200,159673
181830,client-71-126.online.apple.com,1995-08-06 14:10:32-04:00,GET,/shuttle/missions/missions.html,HTTP/1.0,200,8677
181831,client-71-126.online.apple.com,1995-08-06 14:10:32-04:00,GET,/shuttle/missions/missions.html,HTTP/1.0,200,8677
181992,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:45-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
181994,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:45-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
181995,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:46-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
181996,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:46-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
181997,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:46-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
181998,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:46-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
182004,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:52-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
182005,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:52-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
182008,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:52-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
182009,ftp-relay.mv.us.adobe.com,1995-08-06 14:15:52-04:00,GET,/history/apollo/apollo-8/apollo-8-info.html,HTTP/1.0,200,1434
183020,www-c2.proxy.aol.com,1995-08-06 14:49:55-04:00,GET,/shuttle/missions/sts-69/mission-sts-69.html,HTTP/1.0,200,11264
183021,www-c2.proxy.aol.com,1995-08-06 14:49:55-04:00,GET,/shuttle/missions/sts-69/mission-sts-69.html,HTTP/1.0,200,11264
183500,www-b2.proxy.aol.com,1995-08-06 15:07:28-04:00,GET,/images/,HTTP/1.0,200,17688
183501,www-b2.proxy.aol.com,1995-08-06 15:07:28-04:00,GET,/images/,HTTP/1.0,200,17688
192413,www-d2.proxy.aol.com,1995-08-06 19:47:15-04:00,GET,/shuttle/missions/sts-78/mission-sts-78.html,HTTP/1.0,200,4714
192414,www-d2.proxy.aol.com,1995-08-06 19:47:15-04:00,GET,/shuttle/missions/sts-78/mission-sts-78.html,HTTP/1.0,200,4714
192547,www-d2.proxy.aol.com,1995-08-06 19:54:55-04:00,GET,/shuttle/missions/61-c/mission-61-c.html,HTTP/1.0,200,8340
192549,www-d2.proxy.aol.com,1995-08-06 19:54:55-04:00,GET,/shuttle/missions/61-c/mission-61-c.html,HTTP/1.0,200,8340
201597,piweba4y.prodigy.com,1995-08-07 01:45:02-04:00,GET,/images/kscmap-small.gif,HTTP/1.0,200,39017
201598,piweba4y.prodigy.com,1995-08-07 01:45:02-04:00,GET,/images/kscmap-small.gif,HTTP/1.0,200,39017
209798,128.159.122.27,1995-08-07 08:05:40-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
209800,128.159.122.27,1995-08-07 08:05:40-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
210548,thetis.fddi4.fu-berlin.de,1995-08-07 08:24:44-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,304,0
210549,thetis.fddi4.fu-berlin.de,1995-08-07 08:24:44-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,304,0
213849,s4.ibk1.austria.eu.net,1995-08-07 09:37:03-04:00,GET,/msfc/team/nasa_team.html,HTTP/1.0,200,973
213850,s4.ibk1.austria.eu.net,1995-08-07 09:37:03-04:00,GET,/msfc/team/nasa_team.html,HTTP/1.0,200,973
213911,s4.ibk1.austria.eu.net,1995-08-07 09:37:41-04:00,GET,/msfc/team/hq.html,HTTP/1.0,200,9329
213912,s4.ibk1.austria.eu.net,1995-08-07 09:37:41-04:00,GET,/msfc/team/hq.html,HTTP/1.0,200,9329
217552,smsbpc10.nmsi.ac.uk,1995-08-07 10:37:08-04:00,GET,"/cgi-bin/imagemap/countdown69?268,69",HTTP/1.0,302,106
217553,smsbpc10.nmsi.ac.uk,1995-08-07 10:37:08-04:00,GET,"/cgi-bin/imagemap/countdown69?268,69",HTTP/1.0,302,106
223226,128.159.140.128,1995-08-07 12:12:13-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
223228,128.159.140.128,1995-08-07 12:12:13-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
224966,163.206.89.4,1995-08-07 12:38:15-04:00,GET,/ksc.html,HTTP/1.0,200,7034
224967,163.206.89.4,1995-08-07 12:38:15-04:00,GET,/ksc.html,HTTP/1.0,200,7034
227904,beavis.b11.ingr.com,1995-08-07 13:15:11-04:00,GET,/history/apollo/apollo-11/apollo-11-patch-smal...,HTTP/1.0,200,11175
227905,beavis.b11.ingr.com,1995-08-07 13:15:11-04:00,GET,/history/apollo/apollo-11/apollo-11-patch-smal...,HTTP/1.0,200,11175
236936,163.206.137.21,1995-08-07 15:31:52-04:00,GET,/images/gemini-logo.gif,HTTP/1.0,200,4452
236938,163.206.137.21,1995-08-07 15:31:52-04:00,GET,/images/gemini-logo.gif,HTTP/1.0,200,4452
237614,163.206.137.21,1995-08-07 15:41:02-04:00,GET,/history/gemini/gemini-ix-a/gemini-ix-a.html,HTTP/1.0,200,3332
237616,163.206.137.21,1995-08-07 15:41:02-04:00,GET,/history/gemini/gemini-ix-a/gemini-ix-a.html,HTTP/1.0,200,3332
242209,duckling.omsi.edu,1995-08-07 16:52:34-04:00,GET,/ksc.html,HTTP/1.0,200,7034
242210,duckling.omsi.edu,1995-08-07 16:52:34-04:00,GET,/ksc.html,HTTP/1.0,200,7034
249454,a-sen.tamu.edu,1995-08-07 20:10:34-04:00,GET,/shuttle/resources/orbiters/orbiters.html,HTTP/1.0,200,2178
249455,a-sen.tamu.edu,1995-08-07 20:10:34-04:00,GET,/shuttle/resources/orbiters/orbiters.html,HTTP/1.0,200,2178
250334,www-b3.proxy.aol.com,1995-08-07 20:39:46-04:00,GET,/images/STS-5.JPG,HTTP/1.0,200,205748
250335,www-b3.proxy.aol.com,1995-08-07 20:39:46-04:00,GET,/images/STS-5.JPG,HTTP/1.0,200,205748
252879,client-71-99.online.apple.com,1995-08-07 21:58:03-04:00,GET,"/cgi-bin/imagemap/astrohome?142,195",HTTP/1.0,302,101
252881,client-71-99.online.apple.com,1995-08-07 21:58:03-04:00,GET,"/cgi-bin/imagemap/astrohome?142,195",HTTP/1.0,302,101
252901,client-71-99.online.apple.com,1995-08-07 21:58:20-04:00,GET,/msfc/description/description.html,HTTP/1.0,200,2470
252905,client-71-99.online.apple.com,1995-08-07 21:58:20-04:00,GET,/msfc/description/description.html,HTTP/1.0,200,2470
259696,hci-sun1.dsto.gov.au,1995-08-08 02:03:25-04:00,GET,/shuttle/missions/sts-62/mission-sts-62.html,HTTP/1.0,200,32768
259698,hci-sun1.dsto.gov.au,1995-08-08 02:03:25-04:00,GET,/shuttle/missions/sts-62/mission-sts-62.html,HTTP/1.0,200,32768
264016,ns.ctcftp.citoh.co.jp,1995-08-08 06:31:00-04:00,GET,/shuttle/missions/sts-1/mission-sts-1.html,HTTP/1.0,200,8495
264017,ns.ctcftp.citoh.co.jp,1995-08-08 06:31:00-04:00,GET,/shuttle/missions/sts-1/mission-sts-1.html,HTTP/1.0,200,8495
265674,w204zrz.zrz.tu-berlin.de,1995-08-08 07:46:36-04:00,GET,/images/KSC-logosmall.gif,HTTP/1.0,200,1204
265675,w204zrz.zrz.tu-berlin.de,1995-08-08 07:46:36-04:00,GET,/images/KSC-logosmall.gif,HTTP/1.0,200,1204
269483,kirj06.htk.fi,1995-08-08 09:24:50-04:00,GET,/shuttle/missions/missions.html,HTTP/1.0,200,8677
269484,kirj06.htk.fi,1995-08-08 09:24:50-04:00,GET,/shuttle/missions/missions.html,HTTP/1.0,200,8677
275303,163.206.25.240,1995-08-08 11:22:34-04:00,GET,/images/MOSAIC-logosmall.gif,HTTP/1.0,200,363
275305,163.206.25.240,1995-08-08 11:22:34-04:00,GET,/images/MOSAIC-logosmall.gif,HTTP/1.0,200,363
275507,165.224.58.27,1995-08-08 11:27:16-04:00,GET,/images/,HTTP/1.0,200,17688
275508,165.224.58.27,1995-08-08 11:27:16-04:00,GET,/images/,HTTP/1.0,200,17688
276723,128.217.61.75,1995-08-08 11:47:03-04:00,GET,/facilities/tour.html,HTTP/1.0,200,3723
276725,128.217.61.75,1995-08-08 11:47:03-04:00,GET,/facilities/tour.html,HTTP/1.0,200,3723
295773,www-a2.proxy.aol.com,1995-08-08 16:27:17-04:00,GET,/htbin/wais.pl?EDFT-02,HTTP/1.0,200,1637
295774,www-a2.proxy.aol.com,1995-08-08 16:27:17-04:00,GET,/htbin/wais.pl?EDFT-02,HTTP/1.0,200,1637
297023,128.159.147.50,1995-08-08 16:45:48-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
297026,128.159.147.50,1995-08-08 16:45:48-04:00,GET,/images/NASA-logosmall.gif,HTTP/1.0,200,786
307400,www-c3.proxy.aol.com,1995-08-08 20:14:20-04:00,GET,/,HTTP/1.0,200,7131
307401,www-c3.proxy.aol.com,1995-08-08 20:14:20-04:00,GET,/,HTTP/1.0,200,7131
307403,www-d3.proxy.aol.com,1995-08-08 20:14:20-04:00,GET,/,HTTP/1.0,200,7131
307405,www-d3.proxy.aol.com,1995-08-08 20:14:20-04:00,GET,/,HTTP/1.0,200,7131
307406,www-b4.proxy.aol.com,1995-08-08 20:14:21-04:00,GET,/,HTTP/1.0,200,7131
307407,www-b4.proxy.aol.com,1995-08-08 20:14:21-04:00,GET,/,HTTP/1.0,200,7131
313085,www-c5.proxy.aol.com,1995-08-08 22:25:15-04:00,GET,/images/263_small.jpg,HTTP/1.0,200,159673
313086,www-c5.proxy.aol.com,1995-08-08 22:25:15-04:00,GET,/images/263_small.jpg,HTTP/1.0,200,159673
318204,www-c3.proxy.aol.com,1995-08-09 00:38:48-04:00,GET,/shuttle/missions/sts-71/sts-71-day-11-highlig...,HTTP/1.0,200,7327
318205,www-c3.proxy.aol.com,1995-08-09 00:38:48-04:00,GET,/shuttle/missions/sts-71/sts-71-day-11-highlig...,HTTP/1.0,200,7327
318225,www-c3.proxy.aol.com,1995-08-09 00:39:37-04:00,GET,/shuttle/missions/sts-71/sts-71-patch.jpg,HTTP/1.0,200,203429
318226,www-c3.proxy.aol.com,1995-08-09 00:39:37-04:00,GET,/shuttle/missions/sts-71/sts-71-patch.jpg,HTTP/1.0,200,203429
318232,www-c3.proxy.aol.com,1995-08-09 00:39:52-04:00,GET,/shuttle/missions/sts-71/sts-71-patch.jpg,HTTP/1.0,200,203429
318233,www-c3.proxy.aol.com,1995-08-09 00:39:52-04:00,GET,/shuttle/missions/sts-71/sts-71-patch.jpg,HTTP/1.0,200,203429
327248,titan02f,1995-08-09 07:50:31-04:00,GET,/statistics/1995/Jul/Jul95.html,HTTP/1.0,200,9084
327249,titan02f,1995-08-09 07:50:31-04:00,GET,/statistics/1995/Jul/Jul95.html,HTTP/1.0,200,9084
327250,titan02f,1995-08-09 07:50:32-04:00,GET,/statistics/1995/Jul/Jul95.html,HTTP/1.0,200,9084
327251,titan02f,1995-08-09 07:50:32-04:00,GET,/statistics/1995/Jul/Jul95.html,HTTP/1.0,200,9084
334870,titan02f,1995-08-09 10:12:36-04:00,GET,/shuttle/missions/sts-70/mission-sts-70.html,HTTP/1.0,200,20304
334871,titan02f,1995-08-09 10:12:36-04:00,GET,/shuttle/missions/sts-70/mission-sts-70.html,HTTP/1.0,200,20304
334872,titan02f,1995-08-09 10:12:36-04:00,GET,/shuttle/missions/sts-70/mission-sts-70.html,HTTP/1.0,200,20304

In [52]:
logs_data.drop_duplicates(inplace=True)

In [53]:
logs_data.duplicated().sum()

np.int64(0)

## FINAL DATA IS READY FOR ANALYSIS

### EXPORT TO CSV FILE

In [54]:
logs_data.to_csv("access_logs.csv", index=False)